# Generated by Django 2.2.1 on 2019-05-29 15:16

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hasker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.FileField(upload_to=hasker.models.user_directory_path)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('author', models.ForeignKey(default=None, on_delete=models.SET(hasker.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='hasker.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.TextField()),
                ('is_best', models.BooleanField(default=False)),
                ('votes', models.SmallIntegerField(default=0)),
                ('author', models.ForeignKey(default=None, on_delete=models.SET(hasker.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('to_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='hasker.Question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
